spring:
  datasource:
    url: jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
